[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
reruns = 2
reruns_delay = 1
addopts =
    --alluredir=reports/allure-results
    -v
    --tb=short
markers =
    smoke: smoke tests
    regression: regression tests
    web: web tests
    api: api tests
    app: mobile app tests
    critical: critical priority tests
    high: high priority tests
    medium: medium priority tests
    low: low priority tests
